name: CI Workflow

on:
  push:
    branches:
      - main

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  workflow-call-ci:
    uses: ./.github/workflows/workflow_call_ci.yaml
    secrets: inherit
  workflow-call-gh-pages:
    uses: ./.github/workflows/workflow_call_gh_pages.yaml
    secrets: inherit
  workflow-call-deploy:
    uses: ./.github/workflows/workflow_call_deploy.yaml
    secrets: inherit

