name: CI Workflow

on:
  push:
    branches:
      - main

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  workflow-call-validate:
    uses: ./.github/workflows/workflow_call_validate.yaml
    secrets: inherit
  workflow-call-gh-pages:
    needs: workflow-call-validate
    uses: ./.github/workflows/workflow_call_gh_pages.yaml
    secrets: inherit
  workflow-call-npm:
    needs: workflow-call-validate
    uses: ./.github/workflows/workflow_call_npm.yaml
    secrets: inherit

