name: CI

on:
  workflow_call: ~
  workflow_dispatch: ~

jobs:
  combined:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Cache Node.js modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run install
        # act requires exact version numbers while github is OK with just major versions
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - name: Repackage for release
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: release:exports
      - name: Rewrite packages.json
        run: |
          find . -type f -name "package.release.json" | while read fname; do
            dirname=`dirname "$fname"`
            mv -f "${dirname}/package.release.json" "{$dirname}/package.json"
          done
      - name: Run build
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build
