# Deploys all packages to NPM
# to run locally `act workflow_dispatch --workflows ".\.github\workflows\workflow_call_npm.yaml"`-s NPM_TOKEN=X

name: NPM

on:
  workflow_call: ~
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Cache Node.js modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run install
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - name: Run build
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build
      - name: Repackage for release
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: release:exports
      - name: Rewrite packages.json
        run: |
          find . -type f -name "package.release.json" | while read fname; do
            dirname=`dirname "$fname"`
            echo "$fname"
            mv -f "${dirname}/package.release.json" "${dirname}/package.json"
          done
      - name: Check everything still works
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: check-types
      - name: Upload @de/base
        uses: actions/upload-artifact@v4
        with:
          name: base
          path: ./packages/base
      - name: Upload @de/fine
        uses: actions/upload-artifact@v4
        with:
          name: define
          path: ./packages/define
      - name: Upload @de/form-react-mobx
        uses: actions/upload-artifact@v4
        with:
          name: deform
          path: ./packages/form-react-mobx

  deploy-base:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: base
      - name: Deploy @de/base
        uses: JS-DevTools/npm-publish@v3
        id: base
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: ${{ steps.base.outputs.type }}
        run: echo ${{ steps.base.outputs.version }}

  deploy-define:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: define
      - name: Deploy @de/fine
        uses: JS-DevTools/npm-publish@v3
        id: define
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: ${{ steps.define.outputs.type }}
        run: echo ${{ steps.define.outputs.version }}

  deploy-deform-react-mobx:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: base
      - name: Deploy @de/form-react-mobx
        uses: JS-DevTools/npm-publish@v3
        id: deform
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: ${{ steps.deform.outputs.type }}
        run: echo ${{ steps.deform.outputs.version }}
