# Deploys all packages to NPM
# to run locally `act workflow_dispatch --workflows ".\.github\workflows\workflow_call_npm.yaml"-s NPM_TOKEN=X`

name: NPM

on:
  workflow_call: ~
  workflow_dispatch: ~

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Cache Node.js modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run install
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - name: Run build
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build
      - name: Repackage for release
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: release:exports
      - name: Rewrite packages.json
        run: |
          find . -type f -name "package.release.json" | while read fname; do
            dirname=`dirname "$fname"`
            echo "$fname"
            mv -f "${dirname}/package.release.json" "${dirname}/package.json"
          done
      - name: Check everything still works
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: check-types

      - name: Is our token there?
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo $NPM_TOKEN | sed 's/./& /g'

      - name: Deploy @@strictly/base
        uses: JS-DevTools/npm-publish@v3
        id: base
        with:
          package: ./packages/base
          token: ${{ secrets.NPM_TOKEN }}

      - name: Deploy @strictly/define
        uses: JS-DevTools/npm-publish@v3
        id: define
        with:
          package: ./packages/define
          token: ${{ secrets.NPM_TOKEN }}

      - name: Deploy @strictly/react-form
        uses: JS-DevTools/npm-publish@v3
        id: react_form
        with:
          package: ./packages/react-form
          token: ${{ secrets.NPM_TOKEN }}
      - name: Deploy Status
        run: |
          echo "${{ steps.base.outputs.name }} ${{ steps.base.outputs.version }} ${{ steps.base.outputs.type }}"
          echo "${{ steps.define.outputs.name }} ${{ steps.define.outputs.version }} ${{ steps.define.outputs.type }}"
          echo "${{ steps.react_form.outputs.name }} ${{ steps.react_form.outputs.version }} ${{ steps.react_form.outputs.type }}"
